#ifndef MUEHLE_MINI_MAX_RETRO_ANALYSIS_ADD_NUM_SUCCEDORS_VARS_H_
#define MUEHLE_MINI_MAX_RETRO_ANALYSIS_ADD_NUM_SUCCEDORS_VARS_H_

namespace muehle {

// Declaration goes here.

}  // namespace muehle

#endif  // MUEHLE_MINI_MAX_RETRO_ANALYSIS_ADD_NUM_SUCCEDORS_VARS_H_
