#ifndef MUEHLE_MINI_MAX_RETRO_ANALYSIS_SUCCESSOR_COUNT_FILE_STORAGE_H_
#define MUEHLE_MINI_MAX_RETRO_ANALYSIS_SUCCESSOR_COUNT_FILE_STORAGE_H_

namespace muehle {

// Declaration goes here.

}  // namespace muehle

#endif  // MUEHLE_MINI_MAX_RETRO_ANALYSIS_SUCCESSOR_COUNT_FILE_STORAGE_H_
